/* Attribution for sound this project did not make, at the bottom of every page.
 *
 * Joshua supplies ambience from Pixabay and asked for it credited in a set form --
 * "Sound Effect by <author> from Pixabay" -- "placed somewhere at the bottom".
 *
 * The lines are NOT written here. reader/credits.json is generated by
 * `python3 scripts/audio.py credits` from the `credit` block of every supplied asset
 * in the registry, so the footer, the repository's AUDIO_CREDITS.md and the audio
 * itself all come from one source and cannot drift apart. Adding a sound and
 * forgetting to credit it is not possible: validation refuses a supplied file that
 * has no credit.
 *
 * Failing quietly is deliberate. A missing credits file must never break the reader,
 * and an empty list must not leave an empty box on the page.
 */
(function () {
  "use strict";

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"']/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
    });
  }

  /* The author and the source are linked where we have their URLs, because that is
     what the Pixabay attribution snippet does -- but the SENTENCE is whatever the
     generator produced, so linking never changes the wording. */
  function linkify(entry) {
    var text = esc(entry.text);
    if (entry.authorUrl) {
      var author = esc(entry.text.split(" by ").pop().split(" from ")[0]);
      text = text.replace(author,
        '<a href="' + esc(entry.authorUrl) + '" target="_blank" rel="noopener">' + author + '</a>');
    }
    if (entry.sourceUrl) {
      var source = esc(entry.text.split(" from ").pop());
      text = text.replace(new RegExp(source + "$"),
        '<a href="' + esc(entry.sourceUrl) + '" target="_blank" rel="noopener">' + source + '</a>');
    }
    return text;
  }

  function render(data) {
    var box = document.getElementById("audio-credits");
    var list = (data && data.attributions) || [];
    if (!box || !list.length) return;
    box.innerHTML =
      '<p class="audio-credits-head">Audio credits</p><ul>' +
      list.map(function (e) {
        return '<li>' + (e.title ? '<em>' + esc(e.title) + '</em> — ' : "") + linkify(e) + '</li>';
      }).join("") + '</ul>';
    box.hidden = false;
  }

  function load() {
    if (!window.fetch) return;
    fetch("./reader/credits.json", { cache: "no-cache" })
      .then(function (r) { return r.ok ? r.json() : null; })
      .then(render)
      .catch(function () { /* no credits file: the footer simply stays as it was */ });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", load);
  } else {
    load();
  }
})();
